version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: example_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - example-service-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_SERVER: db:5432
    depends_on:
      db:
        condition: service_healthy
    networks:
        - example-service-network
networks:
    example-service-network:
        driver: bridge
