server:
  port: 9578
spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost:5432}/example_service
    username: postgres
    password: SXAQ?Y6D3#AtPeCn
  liquibase:
    contexts: prod
logging:
  level:
    com.insy2s: INFO
    org.springframework.web: INFO
