server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost:5432}/example_service
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    contexts: dev, faker
logging:
  level:
    liquibase: INFO
    com.insy2s: DEBUG
    org.springframework.web: DEBUG
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
